import Logo1 from "./ufas-log.png"
import Logo2 from "./logoforslider.png"
import Texture from "./islamic-texture.jpg"
import IslamicTex from "./islamictexture.png"
import ConferenceImg from "./conference.jpg"
import Bodytexture from "./bodytexture.png"
import HIC from "./HIC.jpg"
import IAFIE from "./IAFIE.jpg"
import ConfImg from "./conferenceimage.png"
export { Logo1, Texture, IslamicTex, ConferenceImg, Bodytexture, HIC, IAFIE, Logo2, ConfImg}